# /docker/Dockerfile.nginx
FROM nginx:alpine

# Remove default Nginx config
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom Nginx config
COPY nginx/nginx.conf /etc/nginx/conf.d/

# Expose port
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]